inherit uboot-sign

UBOOT_SIGN_KEYDIR = "${DEPLOYDIR}"
UBOOT_SIGN_KEYNAME = "uboot-sig" 
UBOOT_MKIMAGE_DTCOPTS = "-I dts -O dtb -p 2000"
UBOOT_SIGN_ENABLE = "1"

UBOOT_FITIMAGE_ENABLE ?= "1"
SPL_SIGN_ENABLE ?= "0"